

-- DO $$
-- DECLARE
--   i INT;
--   j INT;
-- BEGIN
--   i := 0;
--   <<externo>>
--   LOOP
--     i := i + 1;
--     EXIT WHEN i > 10;
--     j := 1;
--     <<interno>>
--     LOOP
--       RAISE NOTICE '%, %', i, j;
--       j := j + 1;
--       -- EXIT WHEN j > 10;
--       -- EXIT externo WHEN j > 5;
--       EXIT WHEN j > 5;
--     END LOOP;
--   END LOOP;
-- END;
-- $$

-- DO $$
-- DECLARE
--   contador INT := 0;
-- BEGIN
--   LOOP
--     contador := contador + 1;
--     EXIT WHEN contador > 100;
--     IF contador % 7 = 0 THEN
--       CONTINUE; --não execute o restante da iteração atual
--     END IF;
--     CONTINUE WHEN contador % 11 = 0;
--     RAISE NOTICE '%', contador;
--   END LOOP;
-- END;
-- $$

--EXIT/WHEN
-- DO $$
-- DECLARE
--   contador INT := 1;
-- BEGIN
--   LOOP
--     RAISE NOTICE '%', contador;
--     contador := contador + 1;
--     EXIT WHEN contador > 10;
--   END LOOP;
-- END;
-- $$
-- DO $$
-- DECLARE
--   contador INT := 1;
-- BEGIN
--   LOOP
--     RAISE NOTICE '%', contador;
--     contador := contador + 1;
--     IF contador > 10 THEN
--       EXIT;
--     END IF;
--   END LOOP;
-- END;
-- $$


-- DO $$
-- BEGIN
--   LOOP
--     RAISE NOTICE 'Testando nosso primeiro loop...';
--   END LOOP;
-- END;
-- $$